### ISSUE TITLE
Docker example

### ISSUE THREAD

**Issue by am-houtkooper** [tomix26/embedded-database-demo#2] opened 2018-07-16 09:26 UTC
Hi,

Great project! Very nice to be able to use an embedded postgres database for tests that go deeper than simple H2-handleable queries and mechanisms.

I'm trying to get this to work with a openjdk:8-jdk-alpine based docker container, but am getting an illegalstateexception when running the tests (that succeed fine outside of docker). I tried creating a non-root user but this didn't solve the issue.

Any ideas? My suggestion is to add a Dockerfile to this demo project to show how it would work.

```
FROM openjdk:8-jdk-alpine

RUN addgroup -S myawesomegroup
RUN adduser -S myawesomeuser -G myawesomegroup
USER myawesomeuser

RUN mkdir /home/myawesomeuser/work
WORKDIR /home/myawesomeuser/work

COPY . .
RUN ./gradlew build
RUN mv ./build/libs/*.jar ./app.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./app.jar"]
```

**Comment by tomix26** [comment] 2018-07-16 23:58
Hi, I think the problem could be caused by using inappropriate parameters in `adduser` command. This has the effect that maven build is still running under root user and embedded database does not start.

Try the following commands instead:
```
RUN addgroup -S -g 1000 myawesomegroup
RUN adduser -D -S -G myawesomegroup -u 1000 -s /bin/ash myawesomeuser
```
If this solves your problem, I will mention it in the documentation.

**Comment by am-houtkooper** [comment] 2018-07-17 07:46
Hi, thanks for the suggestion. Sadly no success on Alpine yet.

This is what I have now:

```
FROM openjdk:8-jdk-alpine

WORKDIR /example

ADD build.gradle /example/build.gradle
ADD gradlew /example/gradlew
ADD gradle  /example/gradle
ADD . /example

RUN adduser --system -s /bin/bash user_who_is_not_root
RUN chown -Rv user_who_is_not_root /example/
USER user_who_is_not_root
RUN ls -l /example

RUN /example/gradlew clean test
```

I have this working example using a larger Debian based image:
```
FROM java:8

WORKDIR /example

ADD build.gradle /example/build.gradle
ADD gradlew /example/gradlew
ADD gradle  /example/gradle
ADD . /example

RUN useradd -ms /bin/bash user_who_is_not_root
RUN chown -Rv user_who_is_not_root /example/
USER user_who_is_not_root
RUN ls -l /example

RUN /example/gradlew clean test
```

What am I doing wrong in the Alpine case?

**Comment by tomix26** [comment] 2018-07-17 20:34
I just tried it and it works well for me. I created the following very simple Dockerfile:
```
FROM openjdk:8-jdk-alpine

RUN addgroup -S -g 1000 test
RUN adduser -D -S -G test -u 1000 -s /bin/ash test

USER test
WORKDIR /home/test
```
Then built the docker image: `docker build -t "zonky/openjdk:8-jdk-alpine" .`

And finally ran it: `docker run -it --rm -v "$(pwd)":/usr/src/project -w /usr/src/project zonky/openjdk:8-jdk-alpine /bin/sh -c "./mvnw clean install"`

Are you sure you are passing **-s /bin/ash** parameter correctly? Further, If you use Grade to build, you can consider using the official gradle docker images. Because these images use non-root user by default. See https://hub.docker.com/_/gradle/

**Comment by am-houtkooper** [comment] 2018-07-18 07:03
Thanks for looking into this together with me.

With your docker file and run-command, replacing `./mvnw clean install` with `./gradlew clean build` I run into the same problem. It may be an issue with the combination of Alpine, Gradle and the embeddded Postgres. Anyhow, I did manage to bring the image down from 1gb to ~700mb by using `opendjk:8-slim-stretch`.

I looked at the gradle alpine docker and that basically does the same thing as you describe, apart from installing gradle of course 😉

I'm going to leave it at that for now. Would love to see an update if you do manage to get a Alpine Gradle example running.

**Comment by tomix26** [comment] 2018-07-20 15:40
I still can not reproduce the problem. Could you please provide your build log?

**Comment by tomix26** [comment] 2018-08-01 09:10
@am-houtkooper Can you please provide your logs? Otherwise, I will have to close this issue.

**Comment by tomix26** [comment] 2018-08-23 13:34
@am-houtkooper Closing for now as no further discussion. Feel free to reopen it, but I need more information.

**Closed by tomix26** 2018-08-23 13:34 UTC
Labels: question
